_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 83
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 83
            "3":
                - 2
                - 23
                - 55
                - 61
            "4": 3.10.8
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
